const datas = [
  {
    firstName: "OyindamolaOyindamolaOyindamolaOyindamola",
    lastName: "Olanrewaju",
    stageName: "oyindamolaaji",
    socialHandle: "@johndoe",
    icon: "tick-circle.svg",
    status: " successful",
    voteCount: 100,
    action: "Action 1",
  },
  {
    firstName: "Newman",
    lastName: "Haruna",
    stageName: "NwmanBad guy",
    socialHandle: "@janesmith",
    icon: "danger.svg ",
    status: "pending",
    voteCount: "0",
    action: "Action 2",
  },
  {
    firstName: "Mike",
    lastName: "Johnson",
    stageName: "Johnny",
    socialHandle: "johnnythebadguy",
    icon: "close-circle.svg",
    status: "decline",
    voteCount: "0",
    action: "Action",
  },
  {
    firstName: "John",
    lastName: "Doe",
    stageName: "JD",
    socialHandle: "@johndoe",
    icon: "tick-circle.svg",
    status: " successful",
    voteCount: 100,
    action: "Action 1",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    stageName: "JS",
    socialHandle: "@janesmith",
    icon: "danger.svg ",
    status: "pending",
    voteCount: "0",
    action: "Action 2",
  },
  {
    firstName: "Mike",
    lastName: "Johnson",
    stageName: "Johnny",
    socialHandle: "johnnythebadguy",
    icon: "close-circle.svg",

    status: "decline",
    voteCount: "0",
    action: "Action",
  },
  {
    firstName: "John",
    lastName: "Doe",
    stageName: "JD",
    socialHandle: "@johndoe",
    icon: "tick-circle.svg",
    status: " successful",
    voteCount: "100",
    action: "Action 1",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    stageName: "JS",
    socialHandle: "@janesmith",
    icon: "danger.svg ",
    status: "pending",
    voteCount: "0",
    action: "Action 2",
  },
  {
    firstName: "Mike",
    lastName: "Johnson",
    stageName: "Johnny",
    socialHandle: "johnnythebadguy",
    icon: "close-circle.svg",

    status: "decline",
    voteCount: "0",
    action: "Action",
  },
  {
    firstName: "John",
    lastName: "Doe",
    stageName: "JD",
    socialHandle: "@johndoe",
    icon: "tick-circle.svg",
    status: " successful",
    voteCount: "100",
    action: "Action 1",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    stageName: "JS",
    socialHandle: "@janesmith",
    icon: "danger.svg ",
    status: "pending",
    voteCount: "0",
    action: "Action 2",
  },
  {
    firstName: "Mike",
    lastName: "Johnson",
    stageName: "Johnny",
    socialHandle: "johnnythebadguy",
    icon: "close-circle.svg",

    status: "decline",
    voteCount: "0",
    action: "Action",
  },
  {
    firstName: "John",
    lastName: "Doe",
    stageName: "JD",
    socialHandle: "@johndoe",
    icon: "tick-circle.svg",
    status: " successful",
    voteCount: "30",
    action: "Action 1",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    stageName: "JS",
    socialHandle: "@janesmith",
    icon: "danger.svg ",
    status: "pending",
    voteCount: "0",
    action: "Action 2",
  },
  {
    firstName: "Mike",
    lastName: "Johnson",
    stageName: "Johnny",
    socialHandle: "johnnythebadguy",
    icon: "close-circle.svg",

    status: "decline",
    voteCount: "0",
    action: "Action",
  },
  {
    firstName: "John",
    lastName: "Doe",
    stageName: "JD",
    socialHandle: "@johndoe",
    icon: "tick-circle.svg",
    status: " successful",
    voteCount: "100",
    action: "Action 1",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    stageName: "JS",
    socialHandle: "@janesmith",
    icon: "danger.svg ",
    status: "pending",
    voteCount: "0",
    action: "Action 2",
  },
  {
    firstName: "Mike",
    lastName: "Johnson",
    stageName: "Johnny",
    socialHandle: "johnnythebadguy",
    icon: "close-circle.svg",

    status: "decline",
    voteCount: "0",
    action: "Action",
  },
];
